[package]
name = "nebokrai-realm"
version = "0.0.0"
edition = "2024"
rust-version = "1.97.1"
license = "AGPL-3.0-only"
publish = false

[dependencies]
nebokrai-shared = { path = "../shared" }
parking_lot = "0.12.5"
tokio = { version = "1.53.1", features = ["macros", "net"] }
walkdir = "2.5.0"
tracing = "0.1.44"
