[package]
name = "nebokrai-zone"
version = "0.0.0"
edition = "2024"
rust-version = "1.97.1"
license = "AGPL-3.0-only"
publish = false

[dependencies]
nebokrai-shared = { path = "../shared" }
indexmap = "2.14.0"
parking_lot = "0.12.5"
slotmap = "1.1.1"
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["macros", "net"] }
tracing = "0.1.44"
