//! Межвладельческая координация божественной кары.
//!
//! Конкретные проверки, часы, формула и wire-снимок принадлежат skill-owner-ам.
//! Здесь остаются регистрация в регионе, упорядоченный снимок клетки,
//! разрешение независимых целей и фактическое применение атаки.
use super::*;
use crate::gameserver::appserver::skills::godpunishmentphalanx::CGodPunishmentPhalanx;
impl CGame {
    pub(crate) fn add_god_punishment_phalanx<R: GameMainLoopRuntime>(&mut self, region: i32, phalanx: CGodPunishmentPhalanx, x: i32, y: i32, now: u32, runtime: &mut R) -> Option<Result<i32, RegionMembershipBlock>> { if self.find_region(region)?.base().skill_cell_block(x, y) == 2 { return None; } let mut owner = self.take_region_owner(region)?; let result = owner.base_mut().add_god_punishment_phalanx(phalanx, x, y, self.area_width, self.area_height, now, runtime); self.restore_region_owner(owner); Some(result) }
    pub(crate) fn send_god_punishment_phalanx_entry<R: GameMainLoopRuntime>(&mut self, region: i32, id: i32, runtime: &mut R) -> Option<()> { let phalanx = self.find_region(region)?.base().find_skill_phalanx(id)?; let SummonedSkillShape::GodPunishment(phalanx) = phalanx else { return None }; let identity = phalanx.shape().identity(); let x = phalanx.shape().get_tile_x().ok()?; let y = phalanx.shape().get_tile_y().ok()?; let payload = phalanx.encode_client_snapshot(|| runtime.now_milliseconds())?; let mut message = CMessage::new(0x000b_f502); message.add_long(identity.object_type); message.add_long(identity.id); message.base_mut().add_guid(identity.ex_id); message.add_long(i32::try_from(payload.len()).ok()?); message.base_mut().add(&payload); message.base_mut().add_char(0); let _ = self.send_shape_position_around(region, x, y, &message); Some(()) }
    pub(super) fn god_punishment_targets(&self, region_id: i32, phalanx: &CGodPunishmentPhalanx) -> Vec<ShapeIdentity> { let Some(region) = self.find_region(region_id).map(ServerRegionOwner::base) else { return Vec::new() }; let (Ok(x), Ok(y)) = (phalanx.shape().get_tile_x(), phalanx.shape().get_tile_y()) else { return Vec::new() }; let mut shapes = Vec::new(); if region.get_shapes(x, y, self.area_width, self.area_height, self, &mut shapes).is_err() { return Vec::new(); } shapes.into_iter().map(|s| s.identity).filter(|i| *i != phalanx.shape().identity() && !(i.object_type == phalanx.master().master_type && i.id == phalanx.master().master_id) && matches!(i.object_type, PLAYER_TYPE | MONSTER_TYPE)).collect() }
    pub(super) fn calculate_god_punishment_attack(&mut self, phalanx: &CGodPunishmentPhalanx, target_level: u8) -> Option<(AttackInformation, PlayerCombatProperties, u8, u8)> { let player = self.find_player(phalanx.master().master_id)?; let combat = player.combat_properties(); let occupation = player.occupation(); let level = player.level(); let weapon = player.equipment().get_goods(2).map_or(0, |g| g.addon_property_value(self.goods_factory(), GAP_WEAPON_DAMAGE_LEVEL, 1)); let (divisor, minimum) = self.globe_setup.weapon_damage_factors(); let delta = weapon.wrapping_sub(i32::from(target_level)).max(0); let factor = if divisor == 0.0 { 1.0 } else { (delta as f32 / divisor).min(1.0).max(minimum) }; let critical = self.globe_setup.critical_rate(); let mut random = |m| game_legacy_random(&mut self.random_state, m); Some(phalanx.calculate_attack(factor, combat, occupation, level, critical, &mut random)) }
}
